# sign.yml
name: 'sign manifest'

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to sign manifest"
        required: true
        default: "https://firmware.ffmuc.net/raw/v2024.4.2_v2022.5.6/sysupgrade/"

jobs:
  sign:
    runs-on: ubuntu-latest
    name: Sign ffmuc manifest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set URL to file
      run: echo "${{ github.event.inputs.url }}" > url.txt
      
    - name: Build docker images
      run: docker build -t gluon:sign .
      
    - name: Run Sign
      id: sign
      run: docker run --rm -t gluon:sign ${{ secrets.privateKey }} >> $GITHUB_STEP_SUMMARY
