# sign.yml
name: 'sign manifest'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**/CODEOWNERS'

jobs:
  sign:
    runs-on: ubuntu-latest
    name: Sign ffmuc manifest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker images
      run: docker build -t gluon:sign .
    - name: Run Sign
      id: sign
      run: docker run --rm -t gluon:sign ${{ secrets.privateKey }}
    - name: Summary
      run: echo ${{ steps.sign.outputs.stdout }} >> $GITHUB_STEP_SUMMARY
