# sign.yml
name: 'sign manifest'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '**/CODEOWNERS'

jobs:
  sign:
    runs-on: ubuntu-latest
    name: Sign ffmuc manifest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker images
      run: docker build -t local .
    - name: Run Sign
      run: docker run --rm -t local ${{ secrets.privateKey }}



